stages:
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  CARGO_HOME: $CI_PROJECT_DIR/cargo

run_tests:
  stage: test
  image: remram/rust
  script:
    - set -e
    - apt-get update
    - apt-get install -y libsqlite3-dev
    - make test
  cache:
    paths:
      - cargo/
      - core/target/
      - program/target/
      - webapp/target/

pages:
  stage: deploy
  image: remram/rust
  services:
    - docker:dind
  script:
    - set -e
    - apt-get update
    - apt-get install -y make git pkg-config libssl1.0-dev
    - curl -Lo /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-17.05.0-ce.tgz && tar -xf /tmp/docker.tgz -C /usr/local && rm /tmp/docker.tgz && export PATH=/usr/local/docker:$PATH && export DOCKER_HOST=tcp://docker:2375
    - export PATH=$CI_PROJECT_DIR/cargo/bin:$PATH
    # Necessary until 0.2.38 gets released with #1275
    - if ! which wasm-bindgen; then (git clone https://github.com/rustwasm/wasm-bindgen.git /tmp/wb && cd /tmp/wb/crates/cli && cargo install --path .); fi
    # - cargo install wasm-bindgen-cli
    - make wasm
    - (cd webapp && ./docker.sh install && ./docker.sh build)
    - mkdir public && cp webapp/dist/* public/
  cache:
    paths:
      - cargo/
      - webapp/target/
      - webapp/node_modules/
  artifacts:
    paths:
      - public
